---
# Общие настройки стенда для любой целевой Debian/Ubuntu VM.
# Ролевые значения по умолчанию лежат в ansible/roles/*/defaults/main.yml.

use_russian_mirrors: true

# Argo CD upstream manifest ссылается на public.ecr.aws Redis image.
# Для российского стенда по умолчанию используем Yandex mirror.
argocd_redis_image_override: "cr.yandex/mirror/library/redis:8.2.3-alpine"

# Первый UI публикуется через HTTPRoute Envoy Gateway.
argocd_server_insecure: true

# Grafana публикуется через Envoy Gateway.
observability_grafana_hostname: grafana.kyverno-mvp.local

# Policy Reporter публикуется через GitOps HTTPRoute.
policy_reporter_hostname: policy-reporter.kyverno-mvp.local

# Root Application для App of Apps по умолчанию смотрит в опубликованный GitHub repository.
# Для fork или private mirror переопределите argocd_root_application_repo_url в inventory/group_vars/extra-vars.
argocd_root_application_path: gitops/apps
