apiVersion: v1
kind: Pod
metadata:
  name: bad-root-pod
  namespace: kyverno-demo
spec:
  containers:
    - name: app
      image: nginx:1.27.4-alpine
      securityContext:
        privileged: false
        runAsUser: 0
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi

