apiVersion: v1
kind: Pod
metadata:
  name: bad-privileged-pod
  namespace: kyverno-demo
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: app
      image: nginx:1.27.4-alpine
      securityContext:
        privileged: true
        runAsNonRoot: true
        runAsUser: 101
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi

