apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/babim-negev/test-task-mts-maga.git
    targetRevision: main
    path: policies/clusterpolicies
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - group: kyverno.io
      kind: ClusterPolicy
      jsonPointers:
        - /spec/admission
        - /spec/emitWarning
      jqPathExpressions:
        - .spec.rules[]?.skipBackgroundRequests
        - .spec.rules[]?.validate.allowExistingViolations
