apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-reporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/policy-reporter
    chart: policy-reporter
    targetRevision: 3.7.4
    helm:
      releaseName: policy-reporter
      values: |
        metrics:
          enabled: true
        plugin:
          kyverno:
            enabled: true
        monitoring:
          enabled: true
          serviceMonitor:
            labels: {}
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ui:
          enabled: true
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: policy-reporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
