apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web-blue
  namespace: kyverno-demo
  labels:
    app: test-web-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-web-blue
  template:
    metadata:
      labels:
        app: test-web-blue
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:1.27.4-alpine
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            runAsUser: 101
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8080
