---
argocd_version: "v3.4.4"
argocd_namespace: argocd
argocd_install_manifest_url: "https://raw.githubusercontent.com/argoproj/argo-cd/{{ argocd_version }}/manifests/install.yaml"
argocd_install_manifest_path: "/tmp/argocd-install-{{ argocd_version }}.yaml"
argocd_install_manifest_timeout: 60
argocd_install_manifest_retries: 5
argocd_install_manifest_delay: 10
argocd_apply_timeout: "360s"
argocd_rollout_timeout: "600s"
argocd_force_apply: false
argocd_redis_image_override: "cr.yandex/mirror/library/redis:8.2.3-alpine"
argocd_redis_upstream_registry_parts:
  - public
  - ecr
  - aws
argocd_redis_upstream_registry: "{{ argocd_redis_upstream_registry_parts | join('.') }}"
argocd_redis_upstream_image_pattern: "{{ argocd_redis_upstream_registry }}/[^\\s\"']*redis:"
argocd_server_insecure: true
argocd_apply_root_application: "{{ argocd_root_application_repo_url | length > 0 }}"
argocd_root_application_name: root
argocd_root_application_project: default
argocd_root_application_repo_url: "https://github.com/babim-negev/test-task-mts-maga.git"
argocd_root_application_target_revision: HEAD
argocd_root_application_path: gitops/apps
