[kyverno_mvp]
# Замените адрес, пользователя и пароль на параметры своей VM.
kyverno-vm ansible_host=192.168.x.x ansible_user=mts ansible_password=mts

[kyverno_mvp:vars]
ansible_python_interpreter=/usr/bin/python3
