---
- name: Проверить целевую VM для Kyverno MVP
  hosts: kyverno_mvp
  become: false
  gather_facts: true

  roles:
    - preflight

- name: Подготовить VM и установить single-node k3s
  hosts: kyverno_mvp
  become: true
  gather_facts: true

  roles:
    - apt_mirrors
    - base
    - k3s
    - helm
    - argocd
    - envoy_gateway
    - observability

  post_tasks:
    - name: Записи для /etc/hosts
      ansible.builtin.pause:
        seconds: 1
        prompt: |-
          {{ ansible_host | default(inventory_hostname) }} {{ envoy_gateway_argocd_hostname }}
          {{ ansible_host | default(inventory_hostname) }} {{ observability_grafana_hostname }}
          {{ ansible_host | default(inventory_hostname) }} {{ policy_reporter_hostname }}
      tags: [etc_hosts]
